#############################################################################
# Makefile for building: test_speech
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon Jul 25 23:10:58 2011
# Project:  test_speech.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile test_speech.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.2/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.2/include/QtCore -I/usr/local/Trolltech/Qt-4.7.2/include/QtGui -I/usr/local/Trolltech/Qt-4.7.2/include -I. -Ifestival/speech_tools/include -Ifestival/festival/src/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.2/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.2/lib -lncurses -L/home/pingu/workspace/QtSpeech/festival/festival/src/lib -lFestival -L/home/pingu/workspace/QtSpeech/festival/speech_tools/lib -lestools -lestbase -leststring -lasound -lQtGui -L/usr/local/Trolltech/Qt-4.7.2/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = QtSpeech_unx.cpp \
		main.cpp \
		widget.cpp moc_QtSpeech.cpp \
		moc_QtSpeech_unx.cpp \
		moc_widget.cpp
OBJECTS       = QtSpeech_unx.o \
		main.o \
		widget.o \
		moc_QtSpeech.o \
		moc_QtSpeech_unx.o \
		moc_widget.o
DIST          = /usr/local/Trolltech/Qt-4.7.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_pre.prf \
		QtSpeech.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/include_source_dir.prf \
		test_speech.pro
QMAKE_TARGET  = test_speech
DESTDIR       = 
TARGET        = test_speech

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test_speech.pro  /usr/local/Trolltech/Qt-4.7.2/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_pre.prf \
		QtSpeech.pri \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.2/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile test_speech.pro
/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_pre.prf:
QtSpeech.pri:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.2/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.2/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile test_speech.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test_speech1.0.0 || $(MKDIR) .tmp/test_speech1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test_speech1.0.0/ && $(COPY_FILE) --parents QtSpeech QtSpeech.h QtSpeech_unx.h widget.h QtSpeech.h .tmp/test_speech1.0.0/ && $(COPY_FILE) --parents QtSpeech_unx.cpp main.cpp widget.cpp .tmp/test_speech1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/test_speech1.0.0/ && (cd `dirname .tmp/test_speech1.0.0` && $(TAR) test_speech1.0.0.tar test_speech1.0.0 && $(COMPRESS) test_speech1.0.0.tar) && $(MOVE) `dirname .tmp/test_speech1.0.0`/test_speech1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test_speech1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_QtSpeech.cpp moc_QtSpeech_unx.cpp moc_widget.cpp moc_QtSpeech.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QtSpeech.cpp moc_QtSpeech_unx.cpp moc_widget.cpp moc_QtSpeech.cpp
moc_QtSpeech.cpp: QtSpeech.h
	/usr/local/Trolltech/Qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) QtSpeech.h -o moc_QtSpeech.cpp

moc_QtSpeech_unx.cpp: QtSpeech \
		QtSpeech.h \
		QtSpeech_unx.h
	/usr/local/Trolltech/Qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) QtSpeech_unx.h -o moc_QtSpeech_unx.cpp

moc_widget.cpp: QtSpeech \
		QtSpeech.h \
		widget.h
	/usr/local/Trolltech/Qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_QtSpeech.cpp: QtSpeech.h
	/usr/local/Trolltech/Qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) QtSpeech.h -o moc_QtSpeech.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/local/Trolltech/Qt-4.7.2/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

QtSpeech_unx.o: QtSpeech_unx.cpp QtSpeech \
		QtSpeech.h \
		QtSpeech_unx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtSpeech_unx.o QtSpeech_unx.cpp

main.o: main.cpp widget.h \
		QtSpeech \
		QtSpeech.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		QtSpeech \
		QtSpeech.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_QtSpeech.o: moc_QtSpeech.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtSpeech.o moc_QtSpeech.cpp

moc_QtSpeech_unx.o: moc_QtSpeech_unx.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtSpeech_unx.o moc_QtSpeech_unx.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

